CREATE TABLE IF NOT EXISTS damage_report (
    id INT AUTO_INCREMENT PRIMARY KEY,
    die_serial_id INT NOT NULL,
    line_id INT NOT NULL,
    product_id INT NOT NULL,
    operator_id INT,
    supervisor_id INT,
    description_dr_id INT NOT NULL,
    explanation_id INT,
    if_sample BOOLEAN DEFAULT FALSE,
    note TEXT,
    status_id INT NOT NULL,
    verdict VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (die_serial_id) REFERENCES die_serial(id),
    FOREIGN KEY (line_id) REFERENCES line_catalog(id),
    FOREIGN KEY (product_id) REFERENCES product_catalog(id),
    FOREIGN KEY (operator_id) REFERENCES worker(id),
    FOREIGN KEY (supervisor_id) REFERENCES worker(id),
    FOREIGN KEY (description_dr_id) REFERENCES description_dr_catalog(id),
    FOREIGN KEY (explanation_id) REFERENCES explanation_catalog(id),
    FOREIGN KEY (status_id) REFERENCES status_catalog(id)
);

CREATE TABLE IF NOT EXISTS die_serial_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    die_serial_id INT NOT NULL,
    status_id INT NOT NULL,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    inner_to_grind DECIMAL(10,2),
    outer_to_grind DECIMAL(10,2),
    note TEXT,
    proudness DECIMAL(10,2),
    inner_grinding DECIMAL(10,2),
    outer_grinding DECIMAL(10,2),
    inner_land_thickness DECIMAL(10,2),
    outer_land_thickness DECIMAL(10,2),
    damage_report_id INT,
    observed_damage_id INT,
    performed_by INT,
    product_id INT,
    line_id INT,
    FOREIGN KEY (die_serial_id) REFERENCES die_serial(id),
    FOREIGN KEY (status_id) REFERENCES status_catalog(id),
    FOREIGN KEY (damage_report_id) REFERENCES damage_report(id),
    FOREIGN KEY (performed_by) REFERENCES worker(id),
    FOREIGN KEY (product_id) REFERENCES product_catalog(id),
    FOREIGN KEY (line_id) REFERENCES line_catalog(id)
);
